services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    env_file:
      - '.wspinapp.env'
    ports:
      - "5432:5432"
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: .
      target: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - /var/log/wspinapp.log:/logs/wspinapp.log
    env_file:
      - '.wspinapp.env'
