version: '3.7'
services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=sprayitwhileyoucanmyfriend
      - POSTGRES_USER=wspinapp
      - POSTGRES_DB=db
  server:
    container_name: server
    restart: "no"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      ~/wspinapp.env