version: '3.7'
services:
  wspinapp_db:
    container_name: wspinapp_db
    image: postgres
    ports:
      - "54321:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  wspinapp:
    restart: "no"
    build: .
    ports:
      - "8080:8080"
      - "54321:5432"
    depends_on:
      - wspinapp_db