version: '3.7'
services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    env_file:
      - '.wspinapp.env'
  server:
    container_name: server
    restart: "no"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - '.wspinapp.env'